### ISSUE TITLE
spawn-wrap is not honoring alternative path's that are passed to spawn when executing node

### ISSUE THREAD

**Issue by TheAlphaNerd** [tapjs/spawn-wrap#38]
if spawn is passed a optional path and told to excute node the alternate path is not being passed to the node shim when it is getting executed. This combined with [only using the basename of node](https://github.com/tapjs/spawn-wrap/blob/master/index.js#L82) causes the wrong version of node to be used.

This is breaking test cases in CITGM where we are testing using alternate node versions in a child process

**Comment by TheAlphaNerd** [comment]
here is an example test that is not passing.

**Comment by TheAlphaNerd** [comment]
it is also worth mentioning that spawn-wrap is ignoring absolute paths to custom node binaries as well

**Comment by addaleax** [comment]
I think you might be running into the caveats described in the [readme](https://github.com/tapjs/spawn-wrap#contracts-and-caveats)?

Do you have any ideas on how spawn-wrap could somewhat reliably check whether the `node` in `PATH` is actually a Node.js executable or not?

**Comment by TheAlphaNerd** [comment]
so there is this in the cavaets

> In order to handle cases where node is invoked in a shell script, the PATH environment variable is modified such that the the shim will be run before the "real" node. However, since Windows does not allow executing shebang scripts like regular programs, a node.cmd file is required.

so the issue I am seeing is that if an alternative PATH is given to the child process this is not being honored. There should be no reason why the path could not be shimmed but still honor the PATH passed to the child_process

**Comment by bcoe** [comment]
@TheAlphaNerd I'm digging through a backlog of OSS work today, and hope to get to this soon. If you have the cycles, a failing test would be amazing.

**Comment by addaleax** [comment]
> If you have the cycles, a failing test would be amazing.

@bcoe https://github.com/TheAlphaNerd/spawn-wrap/commit/81529712dc7c8a524f8a2f0941ba94ce166c1a23

@TheAlphaNerd `spawn-wrap` currently works by adding a custom `node` executable on the `PATH` itself – so this *is* tricky to address…

Btw, the caveat I was referring to was “It *is* possible to escape the wrapping, if you spawn a bash script, and that script modifies the `PATH`, and then calls a specific `node` binary explicitly.” – that seems to describe what you are trying to do, if I haven’t misunderstood?

**Comment by TheAlphaNerd** [comment]
Another test case would be for the other edge case of passing a direct path to node

```js
  t.test('custom path', function (t) {
    var child = cp.spawn(path.join(__dirname, 'fixtures', 'node'), [fixture, 'xyz']);

    child.on('close', function (code) {
      t.equal(code, 1)
      t.end()
    })
})
```

**Comment by bcoe** [comment]
@addaleax @TheAlphaNerd I wonder, could we do something like we do with the npm bin (I believe?) and use `which` to determine if we're actually invoking the instrumented node, replacing the exec if not?

**Comment by TheAlphaNerd** [comment]
that was the solution I was thinking about initially... but will that work
if the path is passed as an argument? I was having a hard time following
where the arguments when in the wrapped call

**Comment by TheAlphaNerd** [comment]
@bcoe any movement on this?

**Comment by bcoe** [comment]
@TheAlphaNerd unfortunately haven't had the opportunity to take a look yet; have it on the top of my stack for `nyc` issues though, just working through an OSS backlog I've managed to collect.

wouldn't complain if someone else took a stab at this (CC: @isaacs) but if no one gets to it, will hopefully have time by end of weekend.

**Comment by TheAlphaNerd** [comment]
no prob! I may take a stab at it myself, but was a little lost with what
happens to the options object when the wrapped process is run

**Comment by bcoe** [comment]
@TheAlphaNerd it's been a good year since I dove into this codebase myself, so I expect to also be lost :p if you start doing any work (which I would greatly appreciate) just open a pull-request ASAP so we can collaborate -- I can also login to the Node IRC for a change.

**Comment by isaacs** [comment]
In the test, you're passing `path` as an option to `cp.spawn()`, but that's not a documented option to spawn.

I'm not sure what this test is supposed to be doing.  Maybe it should be doing `{env:{PATH:...}}`?

**Comment by isaacs** [comment]
Ok, so, reading through the conversation, it looks like what you're looking for is a way to call node while opting out of the spawn-wrapping behavior.

However, there is no way to do that with this module, by design.  It works by setting the `PATH` environment variable in child processes, and also by hijacking any `spawn` that executes anything named `node`.  It is designed to not only do this 100% of the time, but also do it in a way that is nearly impossible to escape or detect.

The only way to escape the wrapping is to execute a non-node program that then edits the `PATH` and/or execs a full path to a different `node` executable.  (For example, `spawn` a bash program that calls `/full/path/to/node`.)

The only reason that works this way is that it is impossible to wrap.

The special case for `npm` exists because `node` insists on hard-coding the shebang line in `npm`'s executable, effectively triggering the escape hatch described above.  I have asked for this behavior to be changed, as it is no longer necessary, and was never really needed.  But, alas, it persists.  So the escape hatch does as well.  If `npm` was any less popular or important in the node world, we wouldn't have to do this.

Rather than force you to write out a bash program and then spawn it, I'd begrudgingly add an explicit escape hatch.  Something like `cp.spawn(..., { turnOffSpawnWrap: true })`.  I would, however, like to make a bet on how long before the first "why is coverage broken!?!" bug to show up as a result ;P

**Comment by TheAlphaNerd** [comment]
@isaacs bah that was a brain fart when writing the test. Even with is set to `{env:{PATH:...}}` we get the failure.

I've updated [my commit](https://github.com/TheAlphaNerd/spawn-wrap/commit/8d9ea9fe0d42afc56018af482c50915037fbba92) accordingly and you should be able to see the two failing edge cases. 

I see you have responded while I've been putting this together so I'm going to go ahead and post this, read your comment, and then edit accordingly

**Comment by TheAlphaNerd** [comment]
OK... so this is making a bit more sense (although I really would love to figure out a bit more how spawn-wrap works... but that is simply out of curiosity).

Is it safe to assume that it owuld not be possible to make a special case for any calls to node that use a full path, and make that the escape hatch? If as you are predicting there is any chance that this could break other code I'd be willing to work a hack into our testing suite to avoid it... it wouldn't be terribly difficult.

**Comment by isaacs** [comment]
> Is it safe to assume that it owuld not be possible to make a special case for any calls to node that use a full path, and make that the escape hatch?

That would be a bad idea.  The most common way to fork or spawn a node child process is `spawn(process.execPath, ...)`, which is always guaranteed to be a full path to a node executable.

Can we zoom out a few levels here?  Why does CITGM need to escape from spawn-wrap?  That's a very specific solution to a problem that I don't think has been fully explored yet.  What's actually happening that you want to not happen?

**Comment by isaacs** [comment]
In other words, rather than "escape wrapping", I suspect that a better solution is "wrap properly", and I'd like to know specifically what that means in your case.  Maybe what we need to do is somehow tell spawn-wrap the executable that _would_ have been called, so that it can exec that one with its wrapper instead of whichever node it's using now.

**Comment by TheAlphaNerd** [comment]
citgm is using spawn for a variety of npm commands. It is possible for us to be running `npm install` using a different binary than `npm install`. we have a [test] (https://github.com/nodejs/citgm/blob/master/test/npm/test-npm-test.js#L150...L168) for a failing case that is passing when we run NYC... which is breaking our coverage. 

I could definitely jerry-rig something in our test suite, but wanted to avoid it if necessary. open to any suggestions you may have, this is a fairly particular edge case

**Comment by isaacs** [comment]
@TheAlphaNerd Aha!  Ok, I understand the bug here.

https://gist.github.com/isaacs/36512d696f11288fc106e67644f0b8f5

When a child process `node` is being replaced with the node from spawn-wrap, then the spawn-wrap script isn't using that copy of node to run the (wrapped with env/argv) using the intended node.

So, that needs to be strung through.  Not by not updating the `PATH`, that mechanism won't work.  But something needs to be done.  It's not trivial, but it is a shortcoming.

In the meantime, I'd just skip that test if coverage is enabled, or don't use coverage, or something.

**Comment by isaacs** [comment]
@TheAlphaNerd Please try `npm i spawn-wrap@next` and see if that fixes the issue.  If so, I'll move it over to the "latest" dist-tag.

**Comment by TheAlphaNerd** [comment]
@isaacs I don't know if this was a publish bug but the lib directory was not published in spawn-wrap@next causing everything to explode

**Comment by bcoe** [comment]
@TheAlphaNerd once you get this tested, mind pinging me over on nyc, I'll get this upstream for you ASAP.

**Comment by TheAlphaNerd** [comment]
will do @bcoe 

@isaacs I've made a branch of citgm that is broken with the current release of spawn-wrap

https://github.com/TheAlphaNerd/citgm/tree/broken-coverage

to reproduce simply clone, install, and run `npm run broken-spawn-wrap`

**Comment by isaacs** [comment]
Yikes, sorry for the hiccup.

Should be fixed now.

**Comment by TheAlphaNerd** [comment]
@isaacs this fixes the problem 🎉

As a heads up it would appear that when you republished you did not publish as next... so nothing to do on your end

@bcoe PR incoming to bump on NYC

**Comment by bcoe** [comment]
@isaacs @TheAlphaNerd one little hiccup:

https://github.com/tapjs/spawn-wrap/blob/master/index.js#L133
